### ISSUE TITLE
premise for detector 

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#18]
Premises for a detector back-end (what one can assume, to be true; for adding in the documentation):

- the first appearance of a thread in the detector will be a fork
- a read or write will never contain a tid, which was not forked before
- reads can happen before writes
- ?a first lock acquire will always happen before the first release?
- happens_after may arrive before a corresponding, happens before arrives -> but no backward sync need
(means no backward synchronisation of a happens_after needed??)
- no double forks of same thread as child
- ...

**Reviews and extension to be made**

**Comment by fmoessbauer** [comment]
Definitely a good point to document this. We should collect the detector relevant promises and document them in the `detector-if` API documentation. Then, it is directly visible to the developer when implementing the interface.

Regarding *happens before*: This should hold in most situations, but we cannot assume / promise that. Maybe we should report this error, but we must not crash here.

**Comment by philip-harr** [comment]
Is therefore a backward synchronisation wanted or do we accept a potential false positive race as long as we are not crashing?

**Comment by fmoessbauer** [comment]
We can accept a false positive in this situation. The HB relation between thread A and B marks a synchronisation point. If the underlying synchronisation behaves correctly, we must not see this as drace flushes the local memory buffer prior to each sync event.

Anyways: Please add a unit test to check that the detector does not crash in this case.

**Comment by philip-harr** [comment]
> Definitely a good point to document this. We should collect the detector relevant promises and document them in the `detector-if` API documentation. Then, it is directly visible to the developer when implementing the interface.
> 
> Regarding _happens before_: This should hold in most situations, but we cannot assume / promise that. Maybe we should report this error, but we must not crash here.

This is done with doxygen comments directly in the detector-if.h or is there a special place for the API documentation?

**Comment by fmoessbauer** [comment]
IMO it's best to document it in the doxygen comments (either directly with each function, or in a preamble).

**Comment by fmoessbauer** [comment]
Premises are now documented in the [detector interface](https://github.com/siemens/drace/blob/master/common/detector/Detector.h#L28).
