### ISSUE TITLE
crash in gp-concurrent-inc when running integration tests with debugger

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#19]
When debugging the drace-test.exe with fasttrack or tsan, gp-concurrent-inc throws an exception in exe_common.inl just after drintegration.h issued the drrun command.

To get the exception. Run a with TSAN or FASTTRACK compiled drace-test.exe with the vs-debugger and wait until the first integration test has started

![image](https://user-images.githubusercontent.com/52499923/63689838-5bb08000-c80b-11e9-945c-3e342ef9e6b0.png)

![image](https://user-images.githubusercontent.com/52499923/63689862-69fe9c00-c80b-11e9-941b-e2ff5c6b1d7d.png)

**Comment by fmoessbauer** [comment]
Please try the following:
- run the gp-concurrent-inc.exe (debug) and check with VS debugger or windbg for errors
- run the gp-concurrent-inc.exe with just dynamorio (in windbg)
- run the gp-concurrent-inc.exe with dynamorio + DRace (in windbg)

Technically, the integration tests just call the corresponding command. See here for details: https://github.com/siemens/drace/blob/master/test/include/DrIntegrationTest.h#L50

**Comment by philip-harr** [comment]
That is a bit strange.
I cannot recreate this error with windbg and even when I use VS Code with the Visual Studio Debugger to run drace-test.exe in the same way as with VS, the exception is not there (at least not shown).

**Comment by fmoessbauer** [comment]
If it just appears in this debugger, this might be not a bug but related to transparency issues of DR. See here for details: https://github.com/DynamoRIO/dynamorio/wiki/Debugging#debugging-on-windows

> The Visual Studio debugger is completely inadequate for debugging applications running under DynamoRIO. It frequently fails due to our manipulation of its injected thread, ...

**Comment by philip-harr** [comment]
Okay, then I'm going to close this here.
