### ISSUE TITLE
Missing destructor call of detector library

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#23]
https://code.siemens.com/multicore/drace/blob/master/drace-client/src/drace-client.cpp#L217

When the detector-dll is unloaded no destructor of the class is called, but just the finalize function. Therefore all allocated members must be destructed manually in the finalize function.

**Comment by fmoessbauer** [comment]
solved in 1e800d0ee95f4f3770a6db796ab3174e8a0b9f59
