### ISSUE TITLE
Add option to start MSR in GUI

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#28]
An option (e.g. checkbox, or button) should be added to the GUI to run a powershell with the MSR.
Here, we should consider, that the MSR is long-running, i.e. it is not terminated after each run. If implemented using a checkbox, we could set the `--once` flag to terminate after drace terminates.

**Comment by philip-harr** [comment]
implemented with 372123333d1aa7bf62d7c284ccc9bdd40629c11f
