### ISSUE TITLE
pipeline is failing for fasttrack detector

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#34]
To be able to load the fasttrack-dll into the drace-tests.exe, some dynamrio dlls must be in the folder of drace-tests.exe. Otherwise all the tests are failing.

These dlls (in .../DynamoRIO/lib64):
![image](https://user-images.githubusercontent.com/52499923/67018003-db1b4b00-f0fa-11e9-858d-aa97078a8b2a.png)

**Comment by fmoessbauer** [comment]
The goal here is to have two separate versions of FT:
- one standalone version which does not depend on DynamoRio (to be used in other projects as well)
- one DR version, which can only be used when running under DRace. There, the DynamoRio dll is already loaded into the memory space

**Comment by philip-harr** [comment]
major problem is fixed since bd857971969e220896522cc41ac9c70e166c8320

but still some integration tests are failing e.g. the lock kinds test

**Comment by philip-harr** [comment]
The lock_kinds test is also sporadically failing with tsan

**Comment by philip-harr** [comment]
resolved with 98087ecb2971e36732886362772acdc72c78b69c
