### ISSUE TITLE
GUI: fix issue with app paths containing spaces

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#35]
Application paths which contain spaces are currently not correctly processed.

![image](https://user-images.githubusercontent.com/9655545/67083347-4ae11280-f19b-11e9-94f9-06167fb1f958.png)

**Comment by philip-harr** [comment]
related to this:
https://stackoverflow.com/questions/9964865/c-system-not-working-when-there-are-spaces-in-two-different-parameters
and that 
https://stackoverflow.com/questions/355988/how-do-i-deal-with-quote-characters-when-using-cmd-exe

clean fix is to just don't use system() but use the actual windows api call e.g. ShellExecute() or CreateProcess()

**Comment by fmoessbauer** [comment]
Fixed in PR 75 (internal)

**Comment by philip-harr** [comment]
closed by 3d65a176568dc4b6e1a0fd14bd8326ae95540741
