### ISSUE TITLE
Non-escaped characters break code preview in html-report in IE+Edge

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#38]
Callstack entries like `::``scalar deleting destructor'` break the code preview as this leads to a javascript crash.

**Possible solution:** escape all callstack entries, file and directory names.

**Comment by fmoessbauer** [comment]
fixed in e5c4a2bb7e532979f105123934b1581702d93a1c

**Comment by fmoessbauer** [comment]
Not fully fixed yet

**Comment by fmoessbauer** [comment]
fd612c54022dd2954da5931c0c9c5ba3b94cd3a8 did fix these issues at least for Firefox. In edge and IE this still does not seem to work.

@philip-harr : Which browsers do we support? Is there anything in the documentation? If the effort is not too large, I would prefer to support also IE and edge.

**Comment by philip-harr** [comment]
IE does not work because template strings "`" are not support by IE and used to contain the code snippets in the html

**Comment by philip-harr** [comment]
in a08065371cd47faa8b3a0d73b199023c4e113850 the issue with the backticks is reolved
ie and edge work now in theory, but for large reports edge has horribly long loading times, ie is slow but okay

still some icons cannot be shown in ie and edge

**Comment by philip-harr** [comment]
d717284b974d461ef388be697605bda758535b53 removes the unsupported in ie and edge unicode chars.
However, edge is still very slow for large reports and should probably not be used.
Chrome and Firefox are fast, IE is okay.
