### ISSUE TITLE
Linux CI-Runner for Cross-Plattform components

### ISSUE THREAD

**Issue by philip-harr** [siemens/drace#39]
Add Jobs to the CI-Pipeline which build and execute the unit tests of the cross platform tools also under linux.

**Comment by fmoessbauer** [comment]
Please also test the 32bit version of FT on linux.

**Comment by fmoessbauer** [comment]
With the latest changes in feature/dracelinux we have rudimentary support for Linux x64 and i386 as well. In the CI, please set `DRACE_ENABLE_RUNTIME=ON`, also on Linux.

To build for i386, `gcc-multiarch` and `g++-multiarch` are required. If they are available, set `CMAKE_C_FLAGS=-m32` and `CMAKE_CXX_FLAGS=-m32`. For boost, probably the package `libboost-filesystem-dev:i386` is required.

**Comment by philip-harr** [comment]
added in f8824631a3c32f8ce121ad0a798fed9f08b068c8
