### ISSUE TITLE
Implement wild-card matching for module names

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#46]
On Linux, module names look like `libc.so.2.6` or `libfoo.1.0.0.so`. To reliably exclude these modules using the config file (or to add custom logic like function interception), we need wildcard matching support.

For example, `libc*` could be use to match `libc.so.x`.

**Comment by philip-harr** [comment]
implemented in aa9378465bc2c3094a2c87f79e83433bfe83b3b0
