### ISSUE TITLE
Write tutorial on how to use drace

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#50]
Write a end-to-end tutorial for new DRace users. This should cover the following topics:

- Get DRace + DynamoRIO
- Non-trivial sample application with a data-race
- How to use the GUI (with screenshots)
- How to interpret the generated report
- How to fix the data-race

The tutorial can be part of either the documentation, or the github repository.

**Comment by philip-harr** [comment]
Add sample app (blackfridayshopping) to package for the tutorial

**Comment by philip-harr** [comment]
Open Topics:

- [ ] Refactor and deploy ShoppingRush project
- [ ] Some pictures are missing
- [ ] gist instance for the pictures
- [ ] refactor typos and spelling misstakes

**Comment by fmoessbauer** [comment]
merged in 4191be0f8f0f9e4873b07e856be09c8b7a3e37da
