### ISSUE TITLE
display symbol information on static variables in HTML report

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#61]
In MR https://github.com/siemens/drace/commit/152a4884a444be6a6b1da8e6d3274903257e0324, support for symbolizing racy memory addresses was added.

While this information is already available in the `DecoratedRace`, it should also be presented in the HTML report. Thereto, the following has to be implemented:

- [x] add an example in mini-apps which races on a static variable
- [x] extend XML report sink to include this into the xml report
- [x] extend ReportConverter to present this information

**Comment by mhmdkanj** [comment]
Writing static vars data to XML report has been tested with gp-concurrent-inc-static.exe sample program + with fasttrack (and not tsan due to #11).

Bug: <file> name cannot be mapped and is thus empty when written to XML file.

**Comment by fmoessbauer** [comment]
@mhmdkanj I just checked what is available in the PDB files, but unfortunately line information for data in .bss or .data is not available.
Nonetheless, for the C# codes this information might be available, so please continue the work here and just fake the data for testing.

**Comment by mhmdkanj** [comment]
Currently, the HTML report shows, if available, Resolved Address info. However, as described in the above comments, `filename`, `line` and `offset` data are placeholders and would thus need to be resolved mapped to their correct values.

**Comment by fmoessbauer** [comment]
implemented in 97f559bb9f534eb709fd0ba8fa59dc4bae9d772f
