### ISSUE TITLE
GUI: broken command when executing drrun.exe

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#62]
The primary command that the **DRaceGUI** runs is broken:

The `drrun.exe` command should be preceded by a `.` in order to execute properly when the path to the executable is given with quotation marks.

For e.g.:

`.'C:/<path_to_drrun>/drrun.exe' -c drace-client.dll -d fasttrack --xml-file test_report.xml -c drace.ini -- test.exe`
rather than:
`'C:/<path_to_drrun>/drrun.exe' -c drace-client.dll -d fasttrack --xml-file test_report.xml -c drace.ini -- test.exe`

**Comment by fmoessbauer** [comment]
Good catch. Thanks for reporting! A workaround would be to use the "copy-to-clipboard" button and manually prefix the command with a dot.

**Comment by fmoessbauer** [comment]
Fixed in 9a01803b8e6e9ae8d0e3f6e6b31d853c8b43d077
