### ISSUE TITLE
Point XML Report to correct src directory

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#63]
As the XML reports are generated, they currently do not point to the correct source directory for DRace.  This would cause the _ReportConverter_ not to preview any relevant code lines.

It is suggested for the ReportConverter to take in src directory(-ies) as arguments + possible caching of the results.

**Comment by fmoessbauer** [comment]
Actually, this is only the case if the executable of the application under test is copied from another system. In this case, the source paths point to locations on the build system and not on the analysis system.

Indeed, it would be great to add support for source relocation, however this should be implemented in the ReportConverter (and not in the XML sink). To get a reasonable performance on large applications with lots of races, we should indeed cache the path-mappings during a single invocation of the ReportConverter.

**Comment by mhmdkanj** [comment]
The Report Converter CLI is extended to take in optional source directories as arguments.
In the case where a source path corresponds to a location on another system (build system) rather than the current one, the source code manager in the Report Converter searches through the given directories and uses those, if the default one is invalid.

**Comment by fmoessbauer** [comment]
Done in 9a01803b8e6e9ae8d0e3f6e6b31d853c8b43d077. Thanks!
