### ISSUE TITLE
Multiple issues around compiling with msbuild instead of ninja

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#65]
When msbuild is used as generator, we run into the following issues:

- build type is not available at configure time => use generator expressions
- TSAN dll is not copied to output directory
- Only non-debug builds work, probably due to missing build type

*note*: This only affects compiling the sources. A workaround is to use the ninja generator.

**Comment by fmoessbauer** [comment]
Actually the build type was not used during configure time in DRace, but unfortunately DynamoRIO does. See #53 for details. By that, the build type at configure time (which is defaulted to release in DynamoRIO + client) does not match the default build type `debug` at compile time.

I now added an assertion notifying that you have to specify the build type at configure time when using MSBuild generator. The other issue with the missing TSAN dll is fixed now.

@ddiefenthaler, could you please check if the patch works for you (branch: `chore/msbuild`)

**Comment by fmoessbauer** [comment]
Fixed in 0e8ecb5

**Comment by ddiefenthaler** [comment]
I have tried the new branch,
and while the configure now correctly works, it fails during the build time.

The issue seems to be the copy of the tsan-dll,
as this fails to create the directory when the build isn't a debug build.

I pushed a fix to the branch `chore/msbuild`.
