### ISSUE TITLE
Extend GUI functionality to take in source directories for Report Converter

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#66]
Report Converter now supports as input directories to source files for applications. This is already implemented in the command line execution of the Report Converter; however, this should be automated with extended functionality in the GUI.

**Comment by fmoessbauer** [comment]
xref #63

**Comment by fmoessbauer** [comment]
implemented in 8c469ec2d4c78905ba6a0ac31f4fbdeb65232241
