### ISSUE TITLE
GUI: Add input to specify program arguments

### ISSUE THREAD

**Issue by fmoessbauer** [siemens/drace#68]
Currently, there is no option in the GUI to start an executable with arguments.
This should be added. Here, we have to take extra care of correct escaping, so please also test that it works with quotes in the option string.

For simple tests, the included gp-cs-sync app can be used.

**Comment by mhmdkanj** [comment]
Hi @fmoessbauer ,
As long as PowerShell is used, entering args that contain a backslash `\` for an executable is fine with or without single-quotes around it. That is, it is not interpreted as an escape character.

It is considered an escape character if for instance I were to run the executable using Gitbash and give it args with no single quotes. If it is wrapped around single quotes, then it is fine as well.

I would say we do not have to take care of escaping the backslash, especially when the application takes in args that could contain a backslash and they are not necessarily windows file paths --- unless you see it from a different angle.

**Comment by fmoessbauer** [comment]
@mhmdkanj : Thanks for the clarification. Yes, that sounds reasonable and I'm fine with it.

**Comment by mhmdkanj** [comment]
done in multicore/drace!145
