### ISSUE TITLE
GUI: add feat to associate saved config file to open GUI app with loaded data

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#69]
The GUI application currently supports the saving and loading of configuration files (i.e. parameters to the drace and report converter apps) in any file format.

The GUI can be extended such that the OS can open these config files as instances to the DraceGUI with the config data automatically filled in.

**Comment by mhmdkanj** [comment]
Implementation:

- [ ] Extend draceGUI exe to be able to take in a config path as an argument, so that a config file could be "Opened With" the draceGUI.

- [ ] Add preferences option to the draceGUI and include in it an option to add a drace config file format to the user's Windows registry

- [ ] Suggest to the user to save a config file in that file type placed in the registry

**Comment by fmoessbauer** [comment]
Implemented in f21eb29f7cf833587ca507b5451fb34cc9e3f4bd
