### ISSUE TITLE
Investigate slow startup performance of ReportConverter

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#75]
The ReportConverter startup is rather slow, therefore some investigation into the reason and possible fix is required.

**Comment by mhmdkanj** [comment]
During the early phases of the execution of the ReportConverter, the `ReportCreator` class at the beginning of its instantiation creates a sub-process that checks whether VS Code is installed or not [vscode is used to open the racy file via an HTML link, otherwise the file is opened in the browser directly]. The relevant lines are shown below:
![subproc](https://user-images.githubusercontent.com/47859951/90766449-d3649e00-e2eb-11ea-9da7-a423c6f193cf.PNG)

The creation and termination of this process on Windows lasts about 0.8 seconds (i.e. about 65% of total ReportConverter execution time), which is very significant.

The profiling data sorted by total internal time is shown below:
![cprof](https://user-images.githubusercontent.com/47859951/90766666-335b4480-e2ec-11ea-908e-f10ebaf82ef8.PNG)

Of course, removing this sub-process creation from the script significantly reduces execution time to less than 0.3 seconds.

In essence, this feature of opening a file from the HTML report via VS Code is convenient - but only if the user has VS Code installed. I would suggest to **remove this feature**, since choosing VS Code to open a file is very specific, and a more general manner to open a file is through the browser (otherwise the user manually opens it since they are given the directory). That is in addition to the fact that if VS Code is in fact installed, the user does not have the option to rather open the file in the browser by Ctrl-clicking. Unless @fmoessbauer you know that the feature is really used extensively by users, we could go ahead and reduce the execution time.

**Comment by fmoessbauer** [comment]
I vote for keeping the Open in VS code functionality, as this is a really convenient feature (it directly jumps to the correct line). Also, 0.8 seconds is not really much and IMO we can live with that.

Did you also try running the converter on larger xml files? I had some situations where it took like 20 seconds to get the report.
Maybe you could just run the profiler again with a larger file.

**Comment by mhmdkanj** [comment]
@fmoessbauer I've never encountered a time when the ReportConverter took that much long (never above 1 sec with the exe's I tried).. is there a specific exe that causes this so that I could reproduce it?

**Comment by fmoessbauer** [comment]
Unfortunately I don't remember which program it was, but I guess that the duration also depends on the number of data-races in the log. If there are hundreds, it might be slow.

Anyways, it's good to know that this performance problem is not a general one. We can perfectly live with an execution time of < 5s. And for larger logs, it's also fine to have a longer exec time. Given that, IMO we can close the issue and revisit if users report 
performance problems in the future.

**Comment by mhmdkanj** [comment]
Yes that makes sense -- the ReportConverter is very File IO bound with writing to the HTML file, so it would be natural to assume slow perf for much larger xml reports.
