### ISSUE TITLE
GUI: Cause GUI to be backward-compatible with older versions of saved configuration files

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#76]
Saved configuration files of older GUI versions might not load in case the GUI was updated [especially when more features that require saving/loading are added or modified]. The issue can be approached by transforming the Data Handler to deal with `json` files rather than statically serialized data.

**Comment by fmoessbauer** [comment]
Good catch! As you said, we could just JSON encode the data into a single object and read back the values we know off.
Ideally, this would make the config file backward and forward compatible.

**Comment by mhmdkanj** [comment]
Any additional features that require saving would be added to this `json` object in the Data Handler as well as the respective updates in Load_Save.

**Comment by mhmdkanj** [comment]
done in https://github.com/siemens/drace/commit/3fa18eaee1022825e262fa5f4facd73dee6186bb
