### ISSUE TITLE
Deployment of DRaceGUI broken in build directory

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#80]
After building the DRaceGUI target, `windeployqt.exe` is executed to deploy the gui app and the corresponding files reside in `build/tools/DRaceGUI/windeployqt/`.

Only part of these files are copied to the project `bin` directory, as claimed in the DRaceGUI `CMakeLists.txt`. It is required that the remaining folders in `/windeployqt` be also copied into the `bin` directory so that the DRaceGUI can be run.

**Comment by fmoessbauer** [comment]
Yes, I assumed that the windeployqt script takes care of that. Apparently that is only the case when building the install target. Manually copying the files in the mentioned folder would be a workaround, as it relies on internal details of the windeployqt script...

Maybe there is an _official_ way to correctly deploy into the build directory?

**Comment by mhmdkanj** [comment]
The `windeployqt.exe` already deploys the app successfully in a temp folder `build/tools/DRaceGUI/windeployqt` to be copied to the installation directory.

So by also copying the files and libs to `build/bin`,  `windeployqt.exe` would be executed once rather than two times, the second being for deployment in the `build/bin` directory.

**Comment by fmoessbauer** [comment]
Implemented in 7a9a3184877d25d353e4a2c4ff9632fa053f949f
