### ISSUE TITLE
Parse detector arguments/options in CLI

### ISSUE THREAD

**Issue by mhmdkanj** [siemens/drace#86]
As all options passed on the command-line are currently registered on DRace, it is useful to have the CLI Runtime Config also parse detector options or arguments.
- For general detector options supported by the detector interface, they can be added manually to the `detector-options` group; e.g. `--heap-only`
- For detector-specific options,  it is required to test if they could be extracted somehow [at runtime] by the interface and parsed accordingly, as the detector itself is also placed as an argument and parsed.

**Comment by mhmdkanj** [comment]
Hi @fmoessbauer , could we safely assume that detector options and DRace options do NOT have any conflicting flag names?
(In case they could, a sentinel flag _might_ be needed when the parser is done parsing detector options.)

**Comment by fmoessbauer** [comment]
> Hi @fmoessbauer , could we safely assume that detector options and DRace options do NOT have any conflicting flag names?
> (In case they could, a sentinel flag _might_ be needed when the parser is done parsing detector options.)

Yes, we can assume that. One exception is flags that are used for both detector and DRace, like `--excl-stack`. This should still be supported.

**Comment by mhmdkanj** [comment]
@fmoessbauer So the goal is that `--excl-stack` can be used at most twice, once for DRace and once for the detection - or in other cases for either one of them; is that correct?

**Comment by fmoessbauer** [comment]
Ideally, the detector is also able to inspect all the flags that where passed to DRace. However, there might be detector-only flags which should not lead to a parse error on the DRace side.

**Comment by mhmdkanj** [comment]
Current solution: Upon specifying the detector using `-d detector` (a requirement), detector-specific flags could be specified after the former flag up UNTIL a DRace flag is recognized.
- Any erroneous flags in between DRace flags is caught by the `RuntimeConfig` parser
- Any erroneous flags within detector-specific flags are expected to be caught by the detector itself (currently not implemented within the given detectors)
- This assumes that there is no conflict in naming between detector-specific flags and DRace flags

The DRaceGUI has also been accommodated with a new dialog which lets the user input detector-specific flags.

**Comment by mhmdkanj** [comment]
Done in https://github.com/siemens/drace/commit/6775c1b308b28fb23eb78ba9657d15bc186530bc
